# Generated by Django 4.2.5 on 2023-10-02 16:38

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/index', validators=[app.validators.file_size]),
        ),
    ]
